name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main  # Change to your default branch name if it's different

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # Set this to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # Set this to the path of your function app project (relative to the repository root)
  PYTHON_VERSION: '3.9'                     # Set this to the Python version to use (e.g., '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        enable-oryx-build: true  # Set to true if your function app needs Oryx build (e.g., Node.js)

    # Optionally, you can add more steps here, such as testing or linting your code.

